### ISSUE TITLE
How to allow the gem to use multiple topics i.e. mutiple bundle id's to send notifications to several different apps?

### ISSUE THREAD

**Issue by Mahesh8** [andrewarrow/p8push#1]
Hi, the Initialize method in the client.rb fetches environment variable APN_BUNDLE_ID i.e the bundle _id for a single app as topic. What if I want to use another Bundle id say APN_VENDOR_BUNDLE_ID as well to send notifications to a different file. Since it accepts only APN_BUNDLE_ID as a topic, I am getting topic disallowed error while sending notifications to a different app with different bundle Id. If you could help me set a dynamic method to choose and send bundle id, it would be helpful!

**Comment by andrewarrow** [comment]
sure, I updated the README:

```
APN = P8push::Client.development
token = 'GETREALTOKENFROMADEVICE'
notification = P8push::Notification.new(device: token)
notification.alert = 'Hello, World!'
notification.topic = 'com.some.other.id' # if you do not want default ENV['APN_BUNDLE_ID'] one
APN.push(notification)
```

So now you can set the topic on the Notification object or if you don't it'll use that default topic
